export const SET_BUSINESS_NAME = 'SET_BUSINESS_NAME';
export const SET_BUSINESS_MAIL = 'SET_BUSINESS_MAIL';
export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_PHONE = 'SET_PHONE';

export const SET_IMAGES = 'SET_IMAGES';
